dist: xenial
language: bash
services: docker
addons:
  apt:
    config:
      retries: true
    update: true
    sources:
      # To install podman and some container tools.
      # https://github.com/containers/libpod/blob/master/install.md
      - sourceline: "ppa:projectatomic/ppa"
    packages:
      # repository: ppa:projectatomic/ppa
      - podman
before_install:
  - podman --version
  - podman version
  - podman info --debug
  - apt-cache show podman
  - dpkg-query -L podman
  - docker --version
  - docker version
  - docker info
matrix:
  include:
    # podman/docker use cases with fedora image.
    # https://hub.docker.com/_/fedora
    # docker
    - name: docker
      install:
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - ls /proc/sys/fs/binfmt_misc/
      script:
        - docker run --rm -t arm64v8/fedora uname -m
    - name: docker-dockerfile
      install:
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - ls /proc/sys/fs/binfmt_misc/
        - docker build --rm -t my-fedora .
      script:
        - docker run --rm -t my-fedora uname -m
    # podman ideal use cases
    # I hope that below 2 use cases replacing above 2 cases works.
    - name: podman
      install:
        - sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - ls /proc/sys/fs/binfmt_misc/
      script:
        - podman run --rm -t arm64v8/fedora uname -m
    - name: podman-dockerfile
      install:
        - sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - ls /proc/sys/fs/binfmt_misc/
        - podman build --rm -t my-fedora .
      script:
        - podman run --rm -t my-fedora uname -m
    # podman use cases to analyze issues.
    - name: podman-own-registries-podman-run
      install:
        - mkdir -p ~/.config/containers
        - cp -p ci/registries.conf ~/.config/containers
      script:
        - podman version
        - podman info --debug
        - podman run --rm -t fedora uname -m
    - name: podman-sudo
      script:
        - podman version
        - podman info --debug
        - sudo podman --log-level debug run --rm docker.io/fedora uname -m
    - name: podman-sudo-privileged
      script:
        - podman version
        - podman info --debug
        - sudo podman --log-level debug run --rm --privileged docker.io/fedora uname -m
    - name: podman-own-registries-sudo-podman-run
      install:
        - mkdir -p ~/.config/containers
        - cp -p ci/registries.conf ~/.config/containers
        - podman version
        - podman info --debug
        - sudo podman --log-level debug run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - ls /proc/sys/fs/binfmt_misc/
      script:
        - echo "OK"
    - name: podman-sudo-podman-run-full-image-with-registry
      install:
        - podman version
        - podman info --debug
        - sudo podman --log-level debug run --rm --privileged docker.io/multiarch/qemu-user-static --reset -p yes
        - ls /proc/sys/fs/binfmt_misc/
      script:
        # https://hub.docker.com/r/arm64v8/fedora/
        - podman run --rm -t docker.io/arm64v8/fedora uname -m
# branches:
#   only:
#     - master
