dist: xenial
language: bash
services: docker
addons:
  apt:
    config:
      retries: true
    update: true
    sources:
      # To install podman.
      # https://github.com/containers/libpod/blob/master/install.md
      - sourceline: "ppa:projectatomic/ppa"
    packages:
      # repository: ppa:projectatomic/ppa
      - podman
before_install:
  # Show version and info.
  - podman --version
  - podman version
  - podman info --debug
  - apt-cache show podman
  - dpkg-query -L podman
  - docker --version
  - docker version
  - docker info

  # Hack podman's configuration files.
  # /etc/containers/registries.conf does not exist.
  # https://clouding.io/kb/en/how-to-install-and-use-podman-on-ubuntu-18-04/
  - mkdir -p /etc/containers
  - sudo echo -e "[registries.search]\nregistries = ['docker.io']" | sudo tee /etc/containers/registries.conf
  - cat /etc/containers/registries.conf
matrix:
  include:
    # podman/docker use cases with fedora image.
    # https://hub.docker.com/_/fedora
    # docker
    - name: "1. docker-qemu"
      install:
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - ls /proc/sys/fs/binfmt_misc/
      script:
        - docker run --rm -t arm64v8/fedora uname -m
    - name: "2. docker-dockerfile-qemu"
      install:
        - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - ls /proc/sys/fs/binfmt_misc/
        - docker build --rm -t my-fedora-arm64 --build-arg BASE_IMAGE=arm64v8/fedora .
      script:
        - docker run --rm -t my-fedora-arm64 uname -m
    # podman
    # Passing with below error message.
    # ERRO[0010] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH
    - name: "3. podman by regular user"
      script:
        - podman run --rm -t fedora uname -m
    - name: "4. podman-dockerfile by regular user"
      install:
        - podman build --rm -t my-fedora .
      script:
        - podman run --rm -t my-fedora uname -m
    - name: "5. podman by root"
      script:
        - sudo podman run --rm -t fedora uname -m
    - name: "6. podman-qemu"
      install:
        - sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - ls /proc/sys/fs/binfmt_misc/
      script:
        - podman run --rm -t arm64v8/fedora uname -m
    - name: "7. podman-dockerfile-qemu"
      install:
        - sudo podman run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - ls /proc/sys/fs/binfmt_misc/
        - podman build --rm -t my-fedora-arm64 --build-arg BASE_IMAGE=arm64v8/fedora .
      script:
        - podman run --rm -t my-fedora-arm64 uname -m
